### ISSUE TITLE
OC v.7.7 update

### ISSUE THREAD

**Issue by fatihdemirbal** [kr4fty/OpenCore-Hackintosh-Asus-PRIME-B460M-A#1]
will you update oc v0.7.7 ?

**Comment by kr4fty** [comment]
Update to OpenCore [0.7.8](https://github.com/kr4fty/OpenCore-Hackintosh-Asus-PRIME-B460M-A/releases/tag/0.7.8)

**Comment by fatihdemirbal** [comment]
thanks

**Comment by kr4fty** [comment]
No problem. If any bug appears please let me know
