### ISSUE TITLE
i5-10400F

### ISSUE THREAD

**Issue by IvanKavaliou** [kr4fty/OpenCore-Hackintosh-Asus-PRIME-B460M-A#2]
Can i start with i5-10400F (this processor dose note have a graphics card)? I have the same board and RX470.

**Comment by kr4fty** [comment]
Español
Deberias modificar el apartado de video y configurarlo para tu placa, [mira esta pagina](https://dortania.github.io/OpenCore-Install-Guide/config.plist/comet-lake.html#deviceproperties)

english:
You should modify the video section and configure it for your board, [check this](https://dortania.github.io/OpenCore-Install-Guide/config.plist/comet-lake.html#deviceproperties)

**Comment by IvanKavaliou** [comment]
Thanks. I can add some options to enable dGPU? Or i can just delete iGUP section?

**Comment by kr4fty** [comment]
I could not tell you, since I use only the integrated graphics.
Maybe this [page](https://www.tonymacx86.com/threads/micro-atx-build-msi-mag-b460m-mortar-i5-10500-rx470-open-core-catalina-big-sur.299709/) can help you for you iGPU

**Comment by IvanKavaliou** [comment]
> Are you install monterey form start or update form Big Sure? I'm asking because i have loop rebooting in the middle of installation. I try install monterey dowloaded from app store.

I found issue, i'm disable secure boot in config and its help to me.

**Comment by kr4fty** [comment]
I did a clean installation

**Comment by kr4fty** [comment]
> > Are you install monterey form start or update form Big Sure? I'm asking because i have loop rebooting in the middle of installation. I try install monterey dowloaded from app store.
> 
> I found issue, i'm disable secure boot in config and its help to me.

Of course, you had to configure the bios previously

**BIOS Settings**
.....
Settings > Boot > Secure Boot > OS Type: Other OS
.....

**Comment by kone9** [comment]
vi que hablas español, ya tengo un EFI compatible con i5 10400f ,rx 6600 xt y mother asus prime b460m-a r2.0 para instalar mac en PC.. Tambien tengo una versiòn de EFI para el sistema operativo, pero aun no la termine de pulir, despues dejo el link por aca

**Comment by kr4fty** [comment]
> vi que hablas español, ya tengo un EFI compatible con i5 10400f ,rx 6600 xt y mother asus prime b460m-a r2.0 para instalar mac en PC.. Tambien tengo una versiòn de EFI para el sistema operativo, pero aun no la termine de pulir, despues dejo el link por aca de unos repositorios con eso

Hola, no tengo GPU externa como para hacer otra EFI y probar

**Comment by kone9** [comment]
> > vi que hablas español, ya tengo un EFI compatible con i5 10400f ,rx 6600 xt y mother asus prime b460m-a r2.0 para instalar mac en PC.. Tambien tengo una versiòn de EFI para el sistema operativo, pero aun no la termine de pulir, despues dejo el link por aca de unos repositorios con eso
> 
> Hola, no tengo GPU externa como para hacer otra EFI y probar

Yo si tengo y la hice funcionar, tengo que subir la EFI, pero aun estoy haciendo pruebas.... despues comparto por aca tambien
![Captura de pantalla 2023-06-05 a la(s) 15 27 05](https://github.com/kr4fty/OpenCore-Hackintosh-Asus-PRIME-B460M-A/assets/12847027/001cc2cb-0fab-497e-889d-34d9ccf237cc)

**Comment by kr4fty** [comment]
Podes hacer un fork del repositorio, agregando el soporte para tu GPU

**Comment by kone9** [comment]
> Podes hacer un fork del repositorio, agregando el soporte para tu GPU

https://www.youtube.com/watch?v=CS630XEUmEo

**Comment by kone9** [comment]
> Podes hacer un fork del repositorio, agregando el soporte para tu GPU

[](https://www.youtube.com/watch?v=CS630XEUmEo)

**Comment by kr4fty** [comment]
> > Podes hacer un fork del repositorio, agregando el soporte para tu GPU
> 
> ya lo descargue y modifique, aunque no hice un fork, el fin de semana lo hago y agrego las modificaciones con mi mother que es el mismo que el tuyo pero el R2.0 que tiene otro audio y otra placa de red.. tambien el teclado es diferente https://www.youtube.com/watch?v=CS630XEUmEo

Muy bueno el video. Con la grafica integrada funciona muy bien tambien (UHD 630), no tambien como el tuyo, pero se la banca.
Lo único que noto es que al iniciar tuve muchísimo consumo de disco (proceso **syspolicyd** ), no se si a vos te ocurre lo mismo

**Comment by kone9** [comment]
> > > Podes hacer un fork del repositorio, agregando el soporte para tu GPU
> > 
> > 
> > ya lo descargue y modifique, aunque no hice un fork, el fin de semana lo hago y agrego las modificaciones con mi mother que es el mismo que el tuyo pero el R2.0 que tiene otro audio y otra placa de red.. tambien el teclado es diferente https://www.youtube.com/watch?v=CS630XEUmEo
> 
> Muy bueno el video. Con la grafica integrada funciona muy bien tambien (UHD 630), no tambien como el tuyo, pero se la banca. Lo único que noto es que al iniciar tuve muchísimo consumo de disco (proceso **syspolicyd** ), no se si a vos te ocurre lo mismo

La verdad que no lo vi a eso.. yo uso un SSD con cable SATA, un M.2 seguro iría mucho más rápido... Fijate de actualizar la EFI, aunque la verdad soy bastante nuevo en esto de mac.. yo segui este video para actulizar el EFI que uso para arranque.. https://www.youtube.com/watch?v=RZF75faxqTQ&t=3s

**Comment by kr4fty** [comment]
Yo tambien use una SSD y en cada actualización también actualizo los kets y las configuraciones de forma manual.

**Comment by kone9** [comment]
> Yo tambien use una SSD y en cada actualización también actualizo los kets y las configuraciones, pero de forma manual.

asi me figura a mi. 
![Captura de pantalla 2023-06-06 a la(s) 00 34 14](https://github.com/kr4fty/OpenCore-Hackintosh-Asus-PRIME-B460M-A/assets/12847027/a834e855-fca2-4c43-ae41-4f2d755d2aad)
