### ISSUE TITLE
will you have a version for i5-10400f and an rx 6600xt?

### ISSUE THREAD

**Issue by kone9** [kr4fty/OpenCore-Hackintosh-Asus-PRIME-B460M-A#5]
Will you have a version for this same mother but with an intel i5-10400f processor and an rx 6600xt graphic? Thanks!

**Comment by kr4fty** [comment]
Similar question [#2](https://github.com/kr4fty/OpenCore-Hackintosh-Asus-PRIME-B460M-A/issues/2)
