### ISSUE TITLE
BIOS version

### ISSUE THREAD

**Issue by cwc329** [kr4fty/OpenCore-Hackintosh-Asus-PRIME-B460M-A#6]
Hi,

Would you mind share your bios version?
I use the same mother board and cpu in my hackintosh build as you do.
I encountered an issue today that after upgrading the bios from v1401 to v1620, my hack stuck in the apple logo when booting.
The boot loader worked fine, I can boot my windows 10 without issues.
The issue was resolve after I downgrade the bios back to v1420.
Your bios version info may help me to debug it.
Thank in advance.

**Comment by kr4fty** [comment]
Hi, it's v1620

I recommend that you load the default configuration in the BIOS and then reconfigure it


### BIOS Settings

Settings > Advanced > System Agent (SA) Configuration > VT-D: **Disabled**
Settings > Advanced > USB Configuration > XHCI Hand-off: **Enabled**
Settings > Advanced > PCI Subsystem Settings > Above 4G Decoding: **Enabled**
Settings > Boot > CSM(Compatibility Support Module) > Launch CSM: **Disabled**
Settings > Boot > Secure Boot > OS Type: **Other OS**
Settings > Boot > Boot\Boot Configuration > Wait For 'F1' If Error: **Disabled**

**Comment by cwc329** [comment]
Thanks for the advise.
I reconfigure from default settings in bios 1620 and now I can successfully boot my hack!
